# Generated by Django 3.2.2 on 2021-05-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='testimonial')),
                ('testimonial', models.TextField()),
            ],
        ),
    ]
