# Generated by Django 3.2.2 on 2021-05-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
